#avatar: assets/img/face.jpg


# Build settings
highlighter: pygments
encoding: utf-8
markdown: kramdown
permalink: pretty
permalink: /404.html

host: localhost
port: 80

sass:
  sass_dir: assets/css
  style: :nested