#avatar: assets/img/face.jpg


# Build settings


permalink: pretty
pageinate: 5


port: 80

sass:
  sass_dir: assets/css
  style: :nested
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
