#avatar: assets/img/face.jpg


# Build settings
highlighter: rouge
encoding: utf-8
markdown: kramdown
permalink: pretty
permalink: /404.html
host: 127.0.0.1
port: 80

sass:
  sass_dir: assets/css
  style: :nested